title: ADPT Document Schema
description: The schemas related to ADPT's Documents.

show_downloads: true

plugins:
  - jekyll-titles-from-headings

# titles_from_headings:
#   enabled: true
#   strip_title: false
#   collections: false

theme: jekyll-theme-cayman
